apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-baremetal-sc-nvme
provisioner: csi-baremetal  # CSI driver name
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  storageType: NVME
  fsType: xfs
