name: Release

on:
  push:
    tags:
      - 'v*'

env:
  builds_url: http://asdrepo.isus.emc.com/artifactory/atlantic-helm-build

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Calculate version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Download Binary
        uses: wei/wget@v1
        with:
          args: ${{ env.builds_url }}/csi-operator/${{ env.RELEASE_VERSION }}/csi-baremetal-operator-${{ env.RELEASE_VERSION }}.tgz

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Github Release create, update, and upload assets
        uses: meeDamian/github-release@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          prerelease: true
          files: ./csi-baremetal-operator-${{ env.RELEASE_VERSION }}.tgz
        if: startsWith(github.ref, 'refs/tags/')

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: /tmp/v${{github.ref}}
