# permissions for end users to edit csibaremetals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csibaremetal-editor-role
rules:
- apiGroups:
  - csi-baremetal.dell.com
  resources:
  - csibaremetals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi-baremetal.dell.com
  resources:
  - csibaremetals/status
  verbs:
  - get
