---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-post-install-script"
  namespace: {{ .Release.Namespace }}
  annotations:
      "helm.sh/hook": post-install
      "helm.sh/hook-weight": "-2"
      "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  post-install.sh: |
    #!/bin/sh
    set -e
    kubectl patch csv -n {{ .Release.Namespace }} {{ .Values.csv.version }} --type='json' -p '[{"op":"replace","path":"/spec/install/spec/deployments/0/spec/template/spec/containers/0/image", "value":"{{ .Values.global.registry }}/{{ .Values.secondaryOperator.image.name }}:{{ default .Values.image.tag .Values.secondaryOperator.image.tag }}"}]'


---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-hook"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-post-install-hook"
      labels:
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "secondaryscheduleroperator.serviceAccountName" . }}
      containers:
        - name: post-install-job
          image: "{{ .Values.global.registry }}/{{ .Values.helmHooks.repository }}:{{ default .Values.image.tag .Values.helmHooks.version }}"
          command:
           - /scripts/post-install.sh
          volumeMounts:
            - name: sh
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: sh
          configMap:
            name: "{{ .Release.Name }}-post-install-script"
            defaultMode: 0555
