---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secondaryscheduleroperator-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - '*'
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  verbs:
  - '*'
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - '*'
