apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi-baremetal
  annotations:
    "helm.sh/resource-policy": keep
spec:
  attachRequired: false
  # pass pod info to NodePublishRequest
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
