{{- if .Values.scheduler.patcher.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scheduler.patcher.config_map_name }}
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: default-scheduler
    algorithmSource:
      policy:
        file:
          path: /etc/kubernetes/manifests/scheduler/policy.yaml
    leaderElection:
      leaderElect: true
    clientConnection:
    {{- if eq .Values.platform "rke" }}
      kubeconfig: /var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
    {{- else }}
      kubeconfig: /etc/kubernetes/scheduler.conf
    {{- end }}
  policy.yaml: |
    apiVersion: v1
    kind: Policy
    extenders:
      - urlPrefix: "http://127.0.0.1:8889"
        filterVerb: filter
        prioritizeVerb: prioritize
        weight: 1
        #bindVerb: bind
        enableHttps: false
        nodeCacheCapable: false
        ignorable: true
        # 15 seconds
        httpTimeout: 15000000000
  config-19.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    extenders:
      - urlPrefix: "http://127.0.0.1:8889"
        filterVerb: filter
        prioritizeVerb: prioritize
        weight: 1
        #bindVerb: bind
        enableHTTPS: false
        nodeCacheCapable: false
        ignorable: true
        # 15 seconds
        httpTimeout: 15s
    leaderElection:
      leaderElect: true
    clientConnection:
    {{- if eq .Values.platform "rke" }}
      kubeconfig: /var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
    {{- else }}
      kubeconfig: /etc/kubernetes/scheduler.conf
    {{- end }}
{{- end }}
