apiVersion: csi-baremetal.dell.com/v1
kind: Deployment
metadata:
  name: csi
  namespace: default
  labels:
    app.kubernetes.io/name: csi-baremetal
    app.kubernetes.io/managed-by: csi-baremetal-operator
    app.kubernetes.io/version: 1.0.0
spec:
  platform: "openshift"
  globalRegistry: ""
  nodeIDAnnotation: true
  nodeSelectors:
    #key: value
  driver:
    controller:
      image:
        name: csi-baremetal-controller
        pullPolicy: Always
        tag: green
      log:
        format: text
        level: info
    node:
      driveMgr:
        image:
          name: csi-baremetal-loopbackmgr
          pullPolicy: Always
          tag: green
        endpoint: tcp://localhost:8888
      image:
        name: csi-baremetal-node
        pullPolicy: Always
        tag: green
      log:
        format: text
        level: info
    metrics:
      path: /metrics
      port: 8787
    logReceiver:
      name: fluent-bit
      image:
        name: fluent-bit
        pullPolicy: Always
        tag: shippable
    deployAlertsConfig: false
  scheduler:
    enable: true
    image:
      name: csi-baremetal-scheduler-extender
      pullPolicy: Always
      tag: green
    log:
      format: text
      level: info
    metrics:
      path: /metrics
      port: 8787
    patcher:
      enable: false
      image:
        name: csi-baremetal-scheduler-patcher
        pullPolicy: Always
        tag: green
      manifest: /etc/kubernetes/manifests/kube-scheduler.yaml
      srcConfigPath: config.yaml
      srcPolicyPath: policy.yaml
      targetConfigPath: /etc/kubernetes/scheduler/config.yaml
      targetPolicyPath: /etc/kubernetes/scheduler/policy.yaml
      interval: 60
      restoreOnShutdown: false
      configMapName: schedulerpatcher-config
    storageProvisioner: csi-baremetal
  operator:
    enable: true
    image:
      name: csi-baremetal-operator
      pullPolicy: Always
      tag: green
    log:
      format: text
      level: info
