apiVersion: v1
kind: ConfigMap
metadata:
  name: schedulerpatcher-config
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: default-scheduler
    algorithmSource:
      policy:
        file:
          path: /etc/kubernetes/scheduler/policy.yaml
    leaderElection:
      leaderElect: true
    clientConnection:
      kubeconfig: /etc/kubernetes/scheduler.conf
  policy.yaml: |
    apiVersion: v1
    kind: Policy
    extenders:
      - urlPrefix: "http://127.0.0.1:8889"
        filterVerb: filter
        prioritizeVerb: prioritize
        weight: 1
        #bindVerb: bind
        enableHttps: false
        nodeCacheCapable: false
        ignorable: true
        # 15 seconds
        httpTimeout: 15000000000
