apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
# CSI driver name
provisioner: csi-baremetal  
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  # With ANY storage type CSI allocates volumes on top of ANY physical drive (non LVG)
  storageType: ANY
  fsType: xfs
