apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}-nvmelvg
# CSI driver name
provisioner: csi-baremetal  
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageType: NVMELVG
  fsType: xfs
