// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// Recorder is an autogenerated mock type for the Recorder type
type Recorder struct {
	mock.Mock
}

// Eventf provides a mock function with given fields: ctx, object, eventtype, reason, messageFmt, args
func (_m *Recorder) Eventf(ctx context.Context, object runtime.Object, eventtype string, reason string, messageFmt string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, object, eventtype, reason, messageFmt)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
